name: New manifest

on: push

jobs:
  messaging_job:
    runs-on: ubuntu-latest
    name: Send message to space channel
   
    steps:
    - name: Send message
      id: manifest
      run: |
        ls -la
        ./scripts/ci/new_manifest_version.sh
